
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 28 12:02:18 MST 2022
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE_STATEMENT = 4;
  public static final int OPER_ART_DIV = 29;
  public static final int IMPRIMIR = 16;
  public static final int OPER_ART_SUMA = 26;
  public static final int CURLY_BRACE_OPEN = 12;
  public static final int OPER_ART_MUL = 28;
  public static final int CICLO_REPETIR = 17;
  public static final int INICIO_CICLO = 21;
  public static final int SEMICOLON = 7;
  public static final int REPETIR_FIN = 19;
  public static final int OPER_ASIG_InDe = 31;
  public static final int IF_STATEMENT = 3;
  public static final int EOF = 0;
  public static final int CURLY_BRACE_CLOSE = 13;
  public static final int error = 1;
  public static final int CICLO_MIENTRAS = 20;
  public static final int FIN_MIENTRAS = 22;
  public static final int ERROR = 36;
  public static final int OPER_AGRUP_CI = 32;
  public static final int NUMBER_INTEGER = 6;
  public static final int OPER_AGRUP_CF = 33;
  public static final int NUMBER_FLOAT = 8;
  public static final int VARIABLE = 2;
  public static final int OPER_REL = 25;
  public static final int OPER_ASIG_IGUAL = 30;
  public static final int LEER = 15;
  public static final int PAL_GRUPO = 14;
  public static final int CONDICION_INICIO = 23;
  public static final int PAREN_CLOSE = 11;
  public static final int VALOR_LOG = 35;
  public static final int OPER_AGRUP_COMA = 34;
  public static final int CONDICION_FIN = 24;
  public static final int REPETIR_HASTA = 18;
  public static final int OPER_ART_RESTA = 27;
  public static final int PAREN_OPEN = 10;
  public static final int VAL_TEXT = 9;
  public static final int IDENTIFIER = 5;
}

