
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 27 21:53:51 MST 2022
//----------------------------------------------------

package Sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPER_ART_DIV = 20;
  public static final int PUNTOYCOMA = 35;
  public static final int IMPRIMIR = 5;
  public static final int OPER_ART_SUMA = 17;
  public static final int CONDICION_SINO = 14;
  public static final int OPER_ART_MUL = 19;
  public static final int CICLO_REPETIR = 6;
  public static final int INICIO_CICLO = 10;
  public static final int REPETIR_FIN = 8;
  public static final int OPER_AGRUP_PI = 23;
  public static final int OPER_ASIG_InDe = 22;
  public static final int OPER_AGRUP_PF = 24;
  public static final int NOMBRE_VAR = 34;
  public static final int OPER_AGRUP_LLI = 25;
  public static final int EOF = 0;
  public static final int PAL_VARIABLE = 2;
  public static final int VALOR_FLO = 31;
  public static final int OPER_AGRUP_LLF = 26;
  public static final int error = 1;
  public static final int CICLO_MIENTRAS = 9;
  public static final int FIN_MIENTRAS = 11;
  public static final int ERROR = 36;
  public static final int OPER_AGRUP_CI = 27;
  public static final int VALOR_STRING = 32;
  public static final int OPER_AGRUP_CF = 28;
  public static final int OPER_REL = 16;
  public static final int OPER_ASIG_IGUAL = 21;
  public static final int LEER = 4;
  public static final int PAL_GRUPO = 3;
  public static final int CONDICION_SI = 12;
  public static final int CONDICION_INICIO = 13;
  public static final int VALOR_LOG = 33;
  public static final int OPER_AGRUP_COMA = 29;
  public static final int VALOR_ENT = 30;
  public static final int CONDICION_FIN = 15;
  public static final int REPETIR_HASTA = 7;
  public static final int OPER_ART_RESTA = 18;
}

